// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameQrFortune = "qr_fortune"

// QrFortune 运势表
type QrFortune struct {
	ID             int64  `gorm:"column:ID;primaryKey;autoIncrement:true" json:"ID"`
	FORTUNESUMMARY string `gorm:"column:FORTUNE_SUMMARY;not null;comment:运情总结" json:"FORTUNE_SUMMARY"` // 运情总结
	LUCKYSTAR      string `gorm:"column:LUCKY_STAR;not null;comment:幸运星" json:"LUCKY_STAR"`            // 幸运星
	SIGNTEXT       string `gorm:"column:SIGN_TEXT;not null;comment:签文" json:"SIGN_TEXT"`               // 签文
	UNSIGNTEXT     string `gorm:"column:UN_SIGN_TEXT;not null;comment:解签" json:"UN_SIGN_TEXT"`         // 解签
}

// TableName QrFortune's table name
func (*QrFortune) TableName() string {
	return TableNameQrFortune
}
