// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"robot-system-server/pkg/db"

	"gorm.io/plugin/soft_delete"
)

const TableNameQrHiddenPoem = "qr_hidden_poem"

// QrHiddenPoem 藏头诗
type QrHiddenPoem struct {
	ID          int64                 `gorm:"column:id;primaryKey;autoIncrement:true;comment:主键" json:"id"`                   // 主键
	Poem        *string               `gorm:"column:poem;comment:诗句内容" json:"poem"`                                           // 诗句内容
	PoemKeyword *string               `gorm:"column:poem_keyword;comment:藏头诗关键字" json:"poemKeyword"`                          // 藏头诗关键字
	PoemNum     int32                 `gorm:"column:poem_num;not null;comment:诗句格式;5五言诗[默认]、7七言诗" json:"poemNum"`             // 诗句格式;5五言诗[默认]、7七言诗
	PoemType    int32                 `gorm:"column:poem_type;not null;comment:藏头位置;1藏头[默认]、2藏尾、3藏中、4递增、5递减" json:"poemType"` // 藏头位置;1藏头[默认]、2藏尾、3藏中、4递增、5递减
	PoemRhyme   int32                 `gorm:"column:poem_rhyme;not null;comment:押韵类型;1双句一压[默认]、2双句押韵、3一三四押" json:"poemRhyme"` // 押韵类型;1双句一压[默认]、2双句押韵、3一三四押
	CreateBy    *string               `gorm:"column:create_by;comment:创建人" json:"createBy"`                                   // 创建人
	CreateTime  *db.LocalDateTime     `gorm:"column:create_time;autoCreateTime;comment:创建时间" json:"createTime"`               // 创建时间
	UpdateBy    *string               `gorm:"column:update_by;comment:更新人" json:"updateBy"`                                   // 更新人
	UpdateTime  *db.LocalDateTime     `gorm:"column:update_time;autoUpdateTime;comment:更新时间" json:"updateTime"`               // 更新时间
	DelFlag     soft_delete.DeletedAt `gorm:"column:del_flag;comment:删除标识;0否1是;softDelete:flag" json:"delFlag"`               // 删除标识;0否1是
}

// TableName QrHiddenPoem's table name
func (*QrHiddenPoem) TableName() string {
	return TableNameQrHiddenPoem
}
