// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import "robot-system-server/pkg/db"

const TableNameQrSpiritSignUDatum = "qr_spirit_sign_u_data"

// QrSpiritSignUDatum 用户灵签数据
type QrSpiritSignUDatum struct {
	ID         int64             `gorm:"column:id;primaryKey;autoIncrement:true;comment:主键" json:"id"`     // 主键
	UserID     *int64            `gorm:"column:user_id;comment:用户ID" json:"userId"`                        // 用户ID
	UserQq     *string           `gorm:"column:user_qq;comment:用户QQ" json:"userQq"`                        // 用户QQ
	SignType   *string           `gorm:"column:sign_type;comment:灵签类型" json:"signType"`                    // 灵签类型
	SignID     *int64            `gorm:"column:sign_id;comment:灵签表ID" json:"signId"`                       // 灵签表ID
	SignDate   *db.LocalDateTime `gorm:"column:sign_date;comment:灵签时间" json:"signDate"`                    // 灵签时间
	CreateBy   *string           `gorm:"column:create_by;comment:创建人" json:"createBy"`                     // 创建人
	CreateTime *db.LocalDateTime `gorm:"column:create_time;autoCreateTime;comment:创建时间" json:"createTime"` // 创建时间
	UpdateBy   *string           `gorm:"column:update_by;comment:更新人" json:"updateBy"`                     // 更新人
	UpdateTime *db.LocalDateTime `gorm:"column:update_time;autoUpdateTime;comment:更新时间" json:"updateTime"` // 更新时间
}

// TableName QrSpiritSignUDatum's table name
func (*QrSpiritSignUDatum) TableName() string {
	return TableNameQrSpiritSignUDatum
}
