// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"robot-system-server/pkg/db"

	"gorm.io/plugin/soft_delete"
)

const TableNameQrSignInDatum = "qr_sign_in_data"

// QrSignInDatum QQ签到表
type QrSignInDatum struct {
	ID         int64                 `gorm:"column:ID;primaryKey;autoIncrement:true;comment:主键" json:"id"`                        // 主键
	Qq         string                `gorm:"column:QQ;not null;comment:用户QQ" json:"qq"`                                           // 用户QQ
	QqNumber   *int64                `gorm:"column:qq_number;comment:QQ号码" json:"qqNumber"`                                       // QQ号码
	Points     int64                 `gorm:"column:POINTS;not null;comment:积分" json:"points"`                                     // 积分
	DayID      int64                 `gorm:"column:DAY_ID;not null;comment:连续签到天数" json:"dayId"`                                  // 连续签到天数
	SignInDate *db.LocalDateTime     `gorm:"column:SIGN_IN_DATE;comment:签到日期" json:"signInDate"`                                  // 签到日期
	UpdateDate *db.LocalDateTime     `gorm:"column:UPDATE_DATE;autoUpdateTime;comment:更新日期" json:"updateDate"`                    // 更新日期
	CreateDate *db.LocalDateTime     `gorm:"column:CREATE_DATE;autoCreateTime;comment:创建日期" json:"createDate"`                    // 创建日期
	CreateBy   *string               `gorm:"column:create_by;comment:创建人" json:"createBy"`                                        // 创建人
	CreateTime *db.LocalDateTime     `gorm:"column:create_time;autoCreateTime;comment:创建时间" json:"createTime"`                    // 创建时间
	UpdateBy   *string               `gorm:"column:update_by;comment:更新人" json:"updateBy"`                                        // 更新人
	UpdateTime *db.LocalDateTime     `gorm:"column:update_time;autoUpdateTime;comment:更新时间" json:"updateTime"`                    // 更新时间
	DelFlag    soft_delete.DeletedAt `gorm:"column:del_flag;not null;default:0;comment:删除标识;0否1是;softDelete:flag" json:"delFlag"` // 删除标识;0否1是
}

// TableName QrSignInDatum's table name
func (*QrSignInDatum) TableName() string {
	return TableNameQrSignInDatum
}
