// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"robot-system-server/pkg/db"
	"time"

	"gorm.io/plugin/soft_delete"
)

const TableNameQrUser = "qr_user"

// QrUser 用户信息表
type QrUser struct {
	UserID      int64                 `gorm:"column:USER_ID;primaryKey;autoIncrement:true;comment:用户ID" json:"userId"`            // 用户ID
	LoginName   *string               `gorm:"column:LOGIN_NAME;comment:登录账号" json:"loginName"`                                    // 登录账号
	UserName    *string               `gorm:"column:USER_NAME;comment:用户昵称" json:"userName"`                                      // 用户昵称
	UserType    *string               `gorm:"column:USER_TYPE;comment:用户类型（00系统用户  , 01 QQ用户）" json:"userType"`                   // 用户类型（00系统用户  , 01 QQ用户）
	UserQq      *string               `gorm:"column:USER_QQ;comment:用户QQ" json:"userQq"`                                          // 用户QQ
	Email       *string               `gorm:"column:EMAIL;comment:用户邮箱" json:"email"`                                             // 用户邮箱
	PhoneNumber *string               `gorm:"column:PHONE_NUMBER;comment:手机号码" json:"phoneNumber"`                                // 手机号码
	Sex         *string               `gorm:"column:SEX;comment:用户性别（0男 1女 2未知）" json:"sex"`                                      // 用户性别（0男 1女 2未知）
	Avatar      *string               `gorm:"column:AVATAR;comment:头像路径" json:"avatar"`                                           // 头像路径
	Password    *string               `gorm:"column:PASSWORD;comment:密码" json:"password"`                                         // 密码
	Salt        *string               `gorm:"column:SALT;comment:盐加密" json:"salt"`                                                // 盐加密
	Status      *string               `gorm:"column:STATUS;comment:帐号状态（1正常 0停用）" json:"status"`                                  // 帐号状态（1正常 0停用）
	DelFlag     soft_delete.DeletedAt `gorm:"column:DEL_FLAG;default:1;comment:删除标志（1代表存在 2代表删除）;softDelete:flag" json:"delFlag"` // 删除标志（1代表存在 2代表删除）
	LoginIP     *string               `gorm:"column:LOGIN_IP;comment:最后登陆IP" json:"loginIp"`                                      // 最后登陆IP
	LoginDate   *time.Time            `gorm:"column:LOGIN_DATE;comment:最后登陆时间" json:"loginDate"`                                  // 最后登陆时间
	CreateBy    *string               `gorm:"column:CREATE_BY;comment:创建者" json:"createBy"`                                       // 创建者
	CreateTime  *db.LocalDateTime     `gorm:"column:CREATE_TIME;autoCreateTime;autoUpdateTime;comment:创建时间" json:"createTime"`    // 创建时间
	UpdateBy    *string               `gorm:"column:UPDATE_BY;comment:更新者" json:"updateBy"`                                       // 更新者
	UpdateTime  *time.Time            `gorm:"column:UPDATE_TIME;comment:更新时间" json:"updateTime"`                                  // 更新时间
	Remark      *string               `gorm:"column:REMARK;comment:备注" json:"remark"`                                             // 备注
}

// TableName QrUser's table name
func (*QrUser) TableName() string {
	return TableNameQrUser
}
