// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wire

import (
	"github.com/google/wire"
	"github.com/spf13/viper"
	"robot-system-server/internal/handler"
	"robot-system-server/internal/repository"
	"robot-system-server/internal/server"
	"robot-system-server/internal/service"
	"robot-system-server/pkg/app"
	"robot-system-server/pkg/jwt"
	"robot-system-server/pkg/log"
	"robot-system-server/pkg/server/http"
	"robot-system-server/pkg/sid"
)

// Injectors from wire.go:

func NewWire(viperViper *viper.Viper, logger *log.Logger) (*app.App, func(), error) {
	jwtJWT := jwt.NewJwt(viperViper)
	handlerHandler := handler.NewHandler(logger)
	db := repository.NewDB(viperViper, logger)
	repositoryRepository := repository.NewRepository(logger, db)
	transaction := repository.NewTransaction(repositoryRepository)
	sidSid := sid.NewSid()
	serviceService := service.NewService(transaction, logger, sidSid, jwtJWT)
	userRepository := repository.NewUserRepository(repositoryRepository)
	userService := service.NewUserService(serviceService, userRepository)
	userHandler := handler.NewUserHandler(handlerHandler, userService)
	beasenRepository := repository.NewBeasenRepository(repositoryRepository)
	beasenService := service.NewBeasenService(serviceService, beasenRepository)
	beasenHandler := handler.NewBeasenHandler(handlerHandler, beasenService)
	fortuneRepository := repository.NewFortuneRepository(repositoryRepository)
	fortuneDataRepository := repository.NewFortuneDataRepository(repositoryRepository)
	fortuneService := service.NewFortuneService(serviceService, fortuneRepository, fortuneDataRepository)
	fortuneHandler := handler.NewFortuneHandler(handlerHandler, fortuneService)
	signInRepository := repository.NewSignInRepository(repositoryRepository)
	userAssetsRepository := repository.NewUserAssetsRepository(repositoryRepository)
	userAssetsService := service.NewUserAssetsService(serviceService, userAssetsRepository, userService)
	signInService := service.NewSignInService(serviceService, signInRepository, userAssetsService)
	signInHandler := handler.NewSignInHandler(handlerHandler, signInService)
	httpServer := server.NewHTTPServer(logger, viperViper, jwtJWT, userHandler, beasenHandler, fortuneHandler, signInHandler)
	job := server.NewJob(logger)
	appApp := newApp(httpServer, job)
	return appApp, func() {
	}, nil
}

// wire.go:

var repositorySet = wire.NewSet(repository.NewDB, repository.NewRepository, repository.NewTransaction, repository.NewUserRepository, repository.NewBeasenRepository, repository.NewFortuneRepository, repository.NewFortuneDataRepository, repository.NewSignInRepository, repository.NewUserAssetsRepository)

var serviceSet = wire.NewSet(service.NewService, service.NewUserService, service.NewBeasenService, service.NewFortuneService, service.NewUserAssetsService, service.NewSignInService)

var handlerSet = wire.NewSet(handler.NewHandler, handler.NewUserHandler, handler.NewBeasenHandler, handler.NewFortuneHandler, handler.NewSignInHandler)

var serverSet = wire.NewSet(server.NewHTTPServer, server.NewJob)

// build App
func newApp(httpServer *http.Server, job *server.Job) *app.App {
	return app.NewApp(app.WithServer(httpServer, job), app.WithName("demo-server"))
}
